name: Project Orion CI

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]
    workflow_dispatch:
      
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: NPM install
              run: npm i --include=dev
            - name: Eslint
              run: npm run eslint ./

