name: Project Orion CI

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: |
                  npm ci
                  npm i jshint
                  node --check index.js
                  jshint index.js
                  cd src
                  node --check arrays.js
                  node --check cmd.js
                  jshint arrays.js
                  jshint cmd.js
